"""schema inicial

Revision ID: e5f1f124bb69
Revises: 
Create Date: 2026-08-12 20:06:47.764539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f1f124bb69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('saldo_inicial_conta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_inicial_guardado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('arquivado', sa.Boolean(), nullable=False),
    sa.Column('arquivado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gastos_fixos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=60), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('dia_vencimento BETWEEN 1 AND 31', name='ck_gf_dia'),
    sa.ForeignKeyConstraint(['ano_id'], ['anos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gastos_fixos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gastos_fixos_ano_id'), ['ano_id'], unique=False)

    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'GUARDADO', 'RETIRADO', 'RENDIMENTO', name='tipolancamento', native_enum=False), nullable=False),
    sa.Column('destino', sa.Enum('CONTA', 'GUARDADO', name='destinorendimento', native_enum=False), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('fitid', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('mes BETWEEN 1 AND 12', name='ck_lancamento_mes'),
    sa.CheckConstraint('valor > 0', name='ck_lancamento_valor_positivo'),
    sa.ForeignKeyConstraint(['ano_id'], ['anos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano_id', 'fitid', name='uq_lancamento_fitid_por_ano')
    )
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamentos_ano_id'), ['ano_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_fitid'), ['fitid'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_tipo'), ['tipo'], unique=False)

    op.create_table('regras_categorizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('padrao', sa.String(length=120), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('padrao')
    )
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano_id', sa.Integer(), nullable=False),
    sa.Column('desejo', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('importancia', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='importancia', native_enum=False), nullable=False),
    sa.Column('somar', sa.Boolean(), nullable=False),
    sa.Column('comprado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ano_id'], ['anos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_ano_id'), ['ano_id'], unique=False)

    op.create_table('gastos_fixos_mensais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gasto_fixo_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Enum('PENDENTE', 'PAGO', name='situacaogastofixo', native_enum=False), nullable=False),
    sa.Column('lancamento_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('mes BETWEEN 1 AND 12', name='ck_gfm_mes'),
    sa.ForeignKeyConstraint(['gasto_fixo_id'], ['gastos_fixos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gasto_fixo_id', 'mes', name='uq_gasto_fixo_mes')
    )
    with op.batch_alter_table('gastos_fixos_mensais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gastos_fixos_mensais_gasto_fixo_id'), ['gasto_fixo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos_fixos_mensais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gastos_fixos_mensais_gasto_fixo_id'))

    op.drop_table('gastos_fixos_mensais')
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_ano_id'))

    op.drop_table('wishlist')
    op.drop_table('regras_categorizacao')
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_tipo'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_mes'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_fitid'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_categoria_id'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_ano_id'))

    op.drop_table('lancamentos')
    with op.batch_alter_table('gastos_fixos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gastos_fixos_ano_id'))

    op.drop_table('gastos_fixos')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    op.drop_table('anos')
    # ### end Alembic commands ###
